### ISSUE TITLE
Not working with Interface builder

### ISSUE THREAD

**Issue by ErAshu** [ivsall2012/AHBannerView#1]
Please fix this. This is not working with storyboard.
I have to use this in UITableviewCell. 

Thanks

**Comment by ivsall2012** [comment]
It's already compatible to the interface builder. You just have to add your bannerView into cell's contentView.

**Comment by ErAshu** [comment]
I have integrate this in cell's contentView. Please find the screenshot. How can i fix this. After scroll this looks good.
![simulator screen shot 10-nov-2017 at 11 37 57 pm](https://user-images.githubusercontent.com/4178384/32672212-3ee3cbd8-c670-11e7-8795-082411fef1d6.png)

**Comment by ivsall2012** [comment]
Can you provide codes for the setup and delegate methods?

**Comment by ErAshu** [comment]
You can download by clicking on this link. 
https://we.tl/tmUFW7fv3r

**Comment by ivsall2012** [comment]
You forgot to set the delegate for each bannerView at the tableView:CellForIndexPath method in your code.  
Though I recommend you to keep track of bannerView setup state. Instead of calling bannerView.setup(...) every time, you should keep track of the setup state and make sure you only call setup(...) only once when there's new data. 
Note: bannerView.setup(...) acts like a refresh method.

And you have to be careful when you write your delegate methods because each tableViewCell's bannerView is different and uses different data. And the delegate methods have no idea which tableView cell is embedded into. You have to find a way to differentiate those bannerViews passed into the delegate methods so that you know which image url should be assigned to which bannerView's imageView.   

Usually I will have only one bannerView and place it at the tableView's headerView, instead of place a bannerView for each tableView cell.

I just did some fix at 0.3.2 so that AHBannerView will react to frame changes dynamically, particularly for tableView cells.
Thanks.
